server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kingxiusam/microservice/ # 配置git仓库的地址
          search-paths: config-repo # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: kingxiusam # git仓库的账号
          password: 926802zhd # git仓库的密码