server:
  port: 8011
spring:
  application:
    name: microservice-com.dong.cloud.consumer-movie-ribbon-with-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka
  instance:
    hostname: ribbon