##构造单点微服务注册中心
#server:
#  port: 8761 #指定该Eureka实例的端口
#eureka:
#  instance:
#    hostname: discovery #指定该Eureka实例的主机名
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#构造高可用微服务注册中心
#---
#spring:
#  profiles: docker0
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: docker0 #指定当profile=docker0时，主机名为docker0
#  client:
#    serviceUrl:
#      defaultZone: http://docker0:8761/eureka/,http://docker1:8762/eureka/      #将自己注册到docker0这个 Eureka上面去
#
#---
#spring:
#  profiles: docker1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: docker1 #指定当profile=docker1时，主机名为docker1
#  client:
#    serviceUrl:
#      defaultZone: http://docker0:8761/eureka/,http://docker1:8761/eureka/      #将自己注册到docker1这个 Eureka上面去
#---

spring:
  profiles: peer1 # 指定profile=peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1 # 指定当profile=peer1时，主机名
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/ # 将自己注册到peer2这个Eureka上面去
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/


