server:
  port: 8021
spring:
  application:
    name: microservice-com.dong.cloud.consumer-movie-feign-with-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  instance:
    hostname: feign